language: ruby

env: RAILS_ENV=test

rvm:
 - 2.5.1

services:
  - postgres

before_script:
  - psql -c 'create database flashcards_2_test;' -U postgres
  - bin/rails db:migrate RAILS_ENV=test
  - cp database.yml.travis config/database.yml
