language: ruby

rvm:
 - 2.5.1

services:
  - postgres

before_script:
  - psql -c 'create database flashcards_2_test;' -U postgres
  - cp database.yml.travis config/database.yml
  - bundle exec rake db:migrate
